# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_report_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_period',
            field=models.IntegerField(choices=[(1, b'daily'), (7, b'weekly'), (30, b'monthly')], null=True),
        ),
    ]
