# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_check_nag_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='nag_time',
            new_name='nag',
        ),
    ]
